### 
POST http://localhost:5000/api/rider/login 
Content-Type: application/json

{ "email" : "test123@gmail.com",
"password" : "Test123@"}

###
POST http://localhost:5000/api/driver/fetch-drivers 
Content-Type: application/json

{ "location": 
{
    "coordinates" :[ 72.9660338, 19.164748 ]}
}

###
GET https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJA4D_CvK45zsRWTZrGK5NKhY&destination=place_id:ChIJJ1vXdxi55zsRpTypIEb-jNg&departure_time=1676712994745&key=AIzaSyBgnDUSbpEJJh-WUl3UJj7_O4Pe8tep0mE
Content-Type: application/json

###
POST http://localhost:5000/api/hotspot/fetch 
Content-Type: application/json

{ "location": 
{
    "coordinates" :[ 72.9660338, 19.164748 ]}
}

###
POST http://localhost:5000/api/driver/rides-data 
Content-Type: application/json

{ "location": 
{
    "coordinates" :[ 72.9660338, 19.164748 ]}
}

###
POST http://localhost:5000/api/ride/fetch-driver-rides
Content-Type: application/json

{ "driverId" : "63dfbc2d4006f4359fb2fd95"
}

###
POST http://localhost:5000/api/driver/rides-data
Content-Type: application/json

{ "driverId" : "63dfbc2d4006f4359fb2fd95",
 "location": { "type": "Point", "coordinates": [ 72.966012, 19.1647128 ]
}
}

###
POST http://localhost:5000/api/ride/user-rides
Content-Type: application/json

{
   "riderId": "63d7e4647010bfd70a5fb142"
}
###
POST http://localhost:5000/api/driver/poolerSearch 
Content-Type: application/json

{
  "rideId": "6414150925a23261d113d976",
  "location": { "type": "Point", "coordinates": [ 72.9660035, 19.1647107 ] },
  "destination": {
    "type": "Point",
    "coordinates": [ 72.97646, 19.185556 ],        
    "_id": "6414150925a23261d113d979"
  }
}

###
POST https://taxifulbackend-1-k1526105.deta.app/api/rider/login 
Content-Type: application/json

{ "email" : "test123@gmail.com",
"password" : "Test123@"}

###
POST https://taxifulbackend-1-k1526105.deta.app/api/ride/user-rides
Content-Type: application/json

{ "riderId": "63d7e4647010bfd70a5fb142"
}
